services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: event-pulse-rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongodb:
    image: mongo:8
    container_name: event-pulse-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mongosh --quiet --username "$${MONGO_INITDB_ROOT_USERNAME}" --password "$${MONGO_INITDB_ROOT_PASSWORD}" --authenticationDatabase admin --eval "db.adminCommand(''ping'').ok" | grep 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongo-express:
    image: mongo-express:1
    container_name: event-pulse-mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: amqp://eventpulse:${RABBITMQ_PASSWORD}@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
  process:
    build:
      context: ./process
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://eventpulse:${MONGO_ROOT_PASSWORD}@mongodb:27017/eventpulse?authSource=admin
      PORT: ${PROCESS_PORT}
      RABBITMQ_URL: amqp://eventpulse:${RABBITMQ_PASSWORD}@rabbitmq:5672
    ports:
      - '${PROCESS_PORT}:${PROCESS_PORT}'
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
  mongodb_data:
